### ISSUE TITLE
Crash when closing the game

### ISSUE THREAD

**Issue by dokara** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.AccessibilityTweaks#7]
For some reason my game crashes after closing the game

the error mainly says AC is the cause

here crash log
```4/16/2023 6:43:24 PM: Critical error occurred in the following mod: accessibilitytweaks@3.2.0
Loaded Mods: bettercrates@1.6.0-rc.1, Ceramos@0.3.1, chiseltools@1.8.3, drdecor@1.2.0, extrachests@1.7.0-pre.1, foundrymod@1.0.0, furniturelibrary@1.0.8, medieval@2.01.02, primitivesurvival@3.1.5, tprunes@1.0.8, translocatorengineeringredux@1.4.1, game@1.18.0-rc.6, zoombuttonreborn@1.4.0, carryon@1.0.0-rc.2, carryonmore@1.5.0, commonlib@2.0.3, hudclock@2.9.0, sailboat@1.0.0, petai@1.6.0, rifteye@0.1.3, creative@1.18.0-rc.6, vsquest@0.4.0, survival@1.18.0-rc.6, xlib@0.7.0-pre.3, accessibilitytweaks@3.2.0, awearablelight@1.0.4, captureanimals@2.5.0, cob@1.0.2, em@2.0.0-pre.5, playercorpse@1.7.1, wolftaming@1.6.0, xskills@0.7.0-pre.5, bricklayers@2.0.0-pre.4
System.MissingMethodException: Method not found: 'Void Vintagestory.API.Client.IShaderProgram.Dispose()'.
   at ApacheTech.VintageMods.AccessibilityTweaks.Features.ColourCorrection.Shaders.ColourCorrectionRenderer.Dispose()
   at ApacheTech.VintageMods.AccessibilityTweaks.Features.ColourCorrection.ColourCorrection.Dispose()
   at ApacheTech.Common.DependencyInjection.ServiceProvider.Dispose()
   at Gantry.Core.DependencyInjection.ModHost.DisposeOnLeaveWorld()
   at ApacheTech.VintageMods.AccessibilityTweaks.Program.Dispose()
   at System.Action.Invoke()
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2544
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 323
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 677
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 292
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 388
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by ApacheTech** [comment]
What version of the game are you using?

The mod will not be updated for 1.18, until 1.18 has a stable release.

**Comment by ApacheTech** [comment]
If you're using 1.17, please post your full log files, then I'll be able to get a better understanding of the issue.

**Comment by dokara** [comment]
> What version of the game are you using?
> 
> The mod will not be updated for 1.18, until 1.18 has a stable release.

Yes I'm on 1.18.0-rc6

**Comment by ApacheTech** [comment]
Ok. I'll add this to the list of things that need fixing for 1.18. Thanks. There will not be any updates for a while though.

**Comment by dokara** [comment]
> Ok. I'll add this to the list of things that need fixing for 1.18. Thanks. There will not be any updates for a while though.

I understand
this mod helps me alot since I have poor vision 
sadly there are crashes currently 

looking forward for the updates

**Comment by ApacheTech** [comment]
Don't worry, I love this mod too. It will definitely be updated. I don't update them early because 1.18 isn't a safe, or stable version of the game. I only release mods for proper, official, stable versions. While 1.18 is still in development, everything can change within days. I want to update the mod once to make it work for 1.18, and the only way I can do that, is to wait until 1.18 is actually released to the public. Really, 1.18 should not be used by the general public, until it is officially released. It's released early for testing purposes only. This will be the same for every mod I have made, and for every version of the game, moving forwards.
